### ISSUE TITLE
Hello, this is a great job. When such a problem occurs at runtime, what is the cause

### ISSUE THREAD

**Issue by LF-Yang** [ttgump/scDCC#2]
Traceback (most recent call last):
  File "D:/Code/scDCC/scDeepCluster.py", line 106, in <module>
    y_pred, _, _, _, _ = model.fit(X=adata.X, X_raw=adata.raw.X, sf=adata.obs.size_factors, y=y, batch_size=args.batch_size, num_epochs=args.maxiter, 
  File "D:\Code\scDCC\scDCC.py", line 154, in fit
    data = self.encodeBatch(X)
  File "D:\Code\scDCC\scDCC.py", line 92, in encodeBatch
    z,_, _, _, _ = self.forward(inputs)
  File "D:\Code\scDCC\scDCC.py", line 69, in forward
    h = self.encoder(x+torch.randn_like(x) * float(self.sigma))
  File "C:\Users\ThinkPad\.conda\envs\DeepL\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\ThinkPad\.conda\envs\DeepL\lib\site-packages\torch\nn\modules\container.py", line 141, in forward
    input = module(input)
  File "C:\Users\ThinkPad\.conda\envs\DeepL\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\ThinkPad\.conda\envs\DeepL\lib\site-packages\torch\nn\modules\linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "C:\Users\ThinkPad\.conda\envs\DeepL\lib\site-packages\torch\nn\functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: expected scalar type Float but found Double

**Comment by ttgump** [comment]
Hi,
It seems the data type of your input X is double. The default data type of model is float, so that is the error. Could you try to convert X to float and run the script again?
